### ISSUE TITLE
java error on receive screen

### ISSUE THREAD

**Issue by lastmeta** [moontreeapp/moontree#431]
### Describe The Bug

when we put request asset in and then start to erase it we get a java error.

### To Reproduce

erase the name

### Expected Behavior

able to erase the name

### Log Output

```shell
I/AssistStructure( 8476): Flattened final assist data: 472 bytes, containing 1 windows, 3 views
E/MethodChannel#flutter/textinput( 8476): Failed to handle method call
E/MethodChannel#flutter/textinput( 8476): java.lang.IndexOutOfBoundsException: invalid selection start: 12
E/MethodChannel#flutter/textinput( 8476): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState.<init>(TextInputChannel.java:782)
E/MethodChannel#flutter/textinput( 8476): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState.fromJson(TextInputChannel.java:738)
E/MethodChannel#flutter/textinput( 8476): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$1.onMethodCall(TextInputChannel.java:103)
E/MethodChannel#flutter/textinput( 8476): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#flutter/textinput( 8476): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
E/MethodChannel#flutter/textinput( 8476): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
E/MethodChannel#flutter/textinput( 8476): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
E/MethodChannel#flutter/textinput( 8476): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#flutter/textinput( 8476): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#flutter/textinput( 8476): 	at android.os.Looper.loop(Looper.java:223)
E/MethodChannel#flutter/textinput( 8476): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/MethodChannel#flutter/textinput( 8476): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/textinput( 8476): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/MethodChannel#flutter/textinput( 8476): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter ( 8476): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(error, invalid selection start: 12, null, java.lang.IndexOutOfBoundsException: invalid selection start: 12
E/flutter ( 8476): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState.<init>(TextInputChannel.java:782)
E/flutter ( 8476): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState.fromJson(TextInputChannel.java:738)
E/flutter ( 8476): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$1.onMethodCall(TextInputChannel.java:103)
E/flutter ( 8476): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/flutter ( 8476): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
E/flutter ( 8476): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
E/flutter ( 8476): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
E/flutter ( 8476): 	at android.os.Handler.handleCallback(Handler.java:938)
E/flutter ( 8476): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter ( 8476): 	at android.os.Looper.loop(Looper.java:223)
E/flutter ( 8476): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/flutter ( 8476): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 8476): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/flutter ( 8476): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter ( 8476): )
E/flutter ( 8476): #0      JSONMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:164
E/flutter ( 8476): #1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:185
E/flutter ( 8476): <asynchronous suspension>
E/flutter ( 8476):
```
### Screenshots

![image](https://user-images.githubusercontent.com/5642485/163254060-af6690ec-c56b-4179-9959-2be4d4d7ef71.png)

**Comment by lastmeta** [comment]
java references the selection so I think its coming from this formatter

```
class MainAssetNameTextFormatter extends TextInputFormatter {
  @override
  TextEditingValue formatEditUpdate(
    TextEditingValue oldValue,
    TextEditingValue newValue,
  ) {
    var text = utils.removeCharsOtherThan(newValue.text.toUpperCase(),
        chars: utils.strings.mainAssetAllowed);
    text = ['RVN', 'RAVEN', 'RAVENCOIN'].contains(text)
        ? ''
        : text
            .replaceAll('..', '.')
            .replaceAll('._', '.')
            .replaceAll('__', '_')
            .replaceAll('_.', '_');
    if (text.startsWith('_') || text.startsWith('.')) {
      text = text.substring(1, text.length);
    }
    if (newValue.text.length == text.length) {
      return newValue.copyWith(text: newValue.text.toUpperCase());
    }
    return TextEditingValue(
      text: text,
      selection: oldValue.selection,
    );
  }
}
```
