### ISSUE TITLE
ping error

### ISSUE THREAD

**Issue by lastmeta** [moontreeapp/moontree#478]
### Describe The Bug

json newline error I've never seen before. happened during 
```
Future<dynamic> ping() async => await request('server.ping');
```

### To Reproduce

run the app?

### Expected Behavior

we shouldn't see this...

### Log Output

```shell
I/flutter ( 4935): TRANSACTIONS DOWNLOADED
I/flutter ( 4935): TRANSACTIONS DOWNLOADED
E/flutter ( 4935): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: FormatException: Unterminated string (at character 3)
E/flutter ( 4935): 45
E/flutter ( 4935):   ^
E/flutter ( 4935):
E/flutter ( 4935): #0      _ChunkedJsonParser.fail
E/flutter ( 4935): #1      _ChunkedJsonParser.close
E/flutter ( 4935): #2      _JsonStringDecoderSink.close
E/flutter ( 4935): #3      _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:81:18)
E/flutter ( 4935): #4      _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
E/flutter ( 4935): #5      _rootRun (dart:async/zone.dart:1418:47)
E/flutter ( 4935): #6      _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter ( 4935): #7      _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter ( 4935): #8      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)
E/flutter ( 4935): #9      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:7)
E/flutter ( 4935): #10     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
E/flutter ( 4935): #11     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
E/flutter ( 4935): #12     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
E/flutter ( 4935): #13     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
E/flutter ( 4935): #14     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:305:20)
E/flutter ( 4935): #15     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:81:18)
E/flutter ( 4935): #16     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
E/flutter ( 4935): #17     _rootRun (dart:async/zone.dart:1418:47)
E/flutter ( 4935): #18     _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter ( 4935): #19     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter ( 4935): #20     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)
E/flutter ( 4935): #21     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:7)
E/flutter ( 4935): #22     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
E/flutter ( 4935): #23     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:782:19)
E/flutter ( 4935): #24     _StreamController._closeUnchecked (dart:async/stream_controller.dart:637:7)
E/flutter ( 4935): #25     _StreamController.close (dart:async/stream_controller.dart:630:5)
E/flutter ( 4935): #26     _Socket._onError (dart:io-patch/socket_patch.dart:2338:19)
E/flutter ( 4935): #27     _rootRunBinary (dart:async/zone.dart:1450:47)
E/flutter ( 4935): #28     _CustomZone.runBinary (dart:async/zone.dart:1342:19)
E/flutter ( 4935): #29     _CustomZone.runBinaryGuarded (dart:async/zone.dart:1252:7)
E/flutter ( 4935): #30     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:360:15)
E/flutter ( 4935): #31     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:375:9)
E/flutter ( 4935): #32     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:280:7)
E/flutter ( 4935): #33     _SyncStreamControllerDispatch._sendError (dart:async/stream_controller.dart:778:19)
E/flutter ( 4935): #34     _StreamController._addError (dart:async/stream_controller.dart:656:7)
E/flutter ( 4935): #35     _StreamController.addError (dart:async/stream_controller.dart:610:5)
E/flutter ( 4935): #36     _RawSecureSocket._reportError (dart:io/secure_socket.dart:771:19)
E/flutter ( 4935): #37     _rootRunBinary (dart:async/zone.dart:1450:47)
E/flutter ( 4935): #38     _CustomZone.runBinary (dart:async/zone.dart:1342:19)
E/flutter ( 4935): #39     _CustomZone.runBinaryGuarded (dart:async/zone.dart:1252:7)
E/flutter ( 4935): #40     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:360:15)
E/flutter ( 4935): #41     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:378:7)
E/flutter ( 4935): #42     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:280:7)
E/flutter ( 4935): #43     _SyncStreamControllerDispatch._sendError (dart:async/stream_controller.dart:778:19)
E/flutter ( 4935): #44     _StreamController._addError (dart:async/stream_controller.dart:656:7)
E/flutter ( 4935): #45     _StreamController.addError (dart:async/stream_controller.dart:610:5)
E/flutter ( 4935): #46     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1852:23)
E/flutter ( 4935): #47     _rootRunBinary (dart:async/zone.dart:1458:13)
E/flutter ( 4935): #48     _CustomZone.runBinary (dart:async/zone.dart:1342:19)
E/flutter ( 4935): #49     _CustomZone.runBinaryGuarded (dart:async/zone.dart:1252:7)
E/flutter ( 4935): #50     _CustomZone.bindBinaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1287:33)
E/flutter ( 4935): #51     _NativeSocket.reportError (dart:io-patch/socket_patch.dart:1562:32)
E/flutter ( 4935): #52     _NativeSocket.multiplex (dart:io-patch/socket_patch.dart:1408:13)
E/flutter ( 4935): #53     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
E/flutter ( 4935):
```

### Tasks For This Bug

 - [ ] #

**Comment by lastmeta** [comment]
saw this only once, not sure why, but it hasn't happened agian, so closing until it shows up again
