### ISSUE TITLE
app freezing unrespoinsive bug

### ISSUE THREAD

**Issue by lastmeta** [moontreeapp/moontree#490]
### Describe The Bug

sometimes when you're using it it becomes unrepsonseive, during scrolling usually 

### To Reproduce

not sure - only happens on device, not emulator.

### Expected Behavior

don't crash

### Log Output

```shell
I/ViewRootImpl@7e70951[MainActivity]( 6300): ViewPostIme pointer 0
D/InsetsSourceConsumer( 6300): setRequestedVisible: visible=true, type=21, host=com.moontree.ravenmobile/com.moontree.ravenmobile.MainActivity, from=android.view.InsetsSourceConsumer.show:235 android.view.InsetsController.collectSourceControls:1207 android.view.InsetsController.controlAnimationUnchecked:1076 android.view.InsetsController.applyAnimation:1455 android.view.InsetsController.applyAnimation:1436 android.view.InsetsController.show:975 android.view.ViewRootImpl$ViewRootHandler.handleMessageImpl:6344 android.view.ViewRootImpl$ViewRootHandler.handleMessage:6269 android.os.Handler.dispatchMessage:106 android.os.Looper.loopOnce:226
D/InsetsSourceConsumer( 6300): setRequestedVisible: visible=true, type=1, host=com.moontree.ravenmobile/com.moontree.ravenmobile.MainActivity, from=android.view.InsetsSourceConsumer.show:235 android.view.InsetsController.showDirectly:1488 android.view.InsetsController.controlAnimationUnchecked:1136 android.view.InsetsController.applyAnimation:1455 android.view.InsetsController.applyAnimation:1436 android.view.InsetsController.show:975 android.view.ViewRootImpl$ViewRootHandler.handleMessageImpl:6344 android.view.ViewRootImpl$ViewRootHandler.handleMessage:6269 android.os.Handler.dispatchMessage:106 android.os.Looper.loopOnce:226
I/ViewRootImpl@7e70951[MainActivity]( 6300): Relayout returned: old=(0,0,1080,2280) new=(0,0,1080,2280) req=(1080,2280)0 dur=4 res=0x1 s={true -5476376651502632688} ch=false fn=145
I/ViewRootImpl@7e70951[MainActivity]( 6300): ViewPostIme pointer 1
E/flutter ( 6300): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: setState() called after dispose(): _TransactionListState#acac1(lifecycle state: defunct, not mounted)
E/flutter ( 6300): This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
E/flutter ( 6300): The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
E/flutter ( 6300): This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
E/flutter ( 6300): #0      State.setState.<anonymous closure>
E/flutter ( 6300): #1      State.setState
E/flutter ( 6300): #2      _TransactionListState.refresh
E/flutter ( 6300): <asynchronous suspension>
E/flutter ( 6300):

════════ Exception caught by gesture ═══════════════════════════════════════════
The following assertion was thrown while handling a gesture:
Navigator operation requested with a context that does not include a Navigator.

The context used to push or pop routes from the Navigator must be that of a widget that is a descendant of a Navigator widget.
When the exception was thrown, this was the stack
#0      Navigator.of.<anonymous closure>
#1      Navigator.of
#2      Navigator.pop
#3      _PageLead.body.<anonymous closure>
#4      _InkResponseState._handleTap
#5      GestureRecognizer.invokeCallback
#6      TapGestureRecognizer.handleTapUp
#7      BaseTapGestureRecognizer._checkUp
#8      BaseTapGestureRecognizer.handlePrimaryPointer
#9      PrimaryPointerGestureRecognizer.handleEvent
#10     PointerRouter._dispatch
#11     PointerRouter._dispatchEventToRoutes.<anonymous closure>
#12     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:539:8)
#13     PointerRouter._dispatchEventToRoutes
#14     PointerRouter.route
#15     GestureBinding.handleEvent
#16     GestureBinding.dispatchEvent
#17     RendererBinding.dispatchEvent
#18     GestureBinding._handlePointerEventImmediately
#19     GestureBinding.handlePointerEvent
#20     GestureBinding._flushPointerEventQueue
#21     GestureBinding._handlePointerDataPacket
#25     _invoke1 (dart:ui/hooks.dart:170:10)
#26     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:331:7)
#27     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
(elided 3 frames from dart:async)
Handler: "onTap"
Recognizer: TapGestureRecognizer#50bb4
    debugOwner: GestureDetector
    state: possible
    won arena
    finalPosition: Offset(38.5, 66.2)
    finalLocalPosition: Offset(38.5, 23.5)
    button: 1
    sent tap down
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture ═══════════════════════════════════════════
Navigator operation requested with a context that does not include a Navigator.
════════════════════════════════════════════════════════════════════════════════
```

### Screenshots

![image](https://user-images.githubusercontent.com/5642485/165154778-f32bb003-6c63-496a-aeb1-1a9bc7310630.png)

### Tasks For This Bug

 - [ ] #

**Comment by lastmeta** [comment]
haven't seen this recently
