### ISSUE TITLE
subscriptionHandles concurrent modification issue

### ISSUE THREAD

**Issue by lastmeta** [moontreeapp/moontree#60]
When we lose connection to the electrum client we re-establish one asap. When the AddressSubscriptionWaiter notices we lost connection it will remove the subscriptionHandles - this is a list of subscriptions, socket connections to electrum that we're listening to, electrum will push us a notification that a transaction has occurred by address. 

it's while we're purging the old client's subscriptions that (I assume) a new connection was made, and new subscriptions are being added. here's the code
```
  Future deinitSubscriptionHandles() async {
    for (var listener in services.client.subscribe.subscriptionHandles.values) { // ERRORS
      await listener.cancel();
    }
    services.client.subscribe.subscriptionHandles.clear();
  }

  void setupClientListener() =>
      listen('streams.client.client', streams.client.client, (client) async {
        if (client == null) {
          await deinitSubscriptionHandles();
        } else {
  ....
```
and here's the error
```
I/flutter ( 6202): ----------------FIREBASE CRASHLYTICS----------------
I/flutter ( 6202): Concurrent modification during iteration: _LinkedHashMap len:0.
I/flutter ( 6202): #0      _CompactIterator.moveNext (dart:collection-patch/compact_hash.dart:476:7)
I/flutter ( 6202): #1      AddressSubscriptionWaiter.deinitSubscriptionHandles (package:raven_back/waiters/address_subscription.dart:29:72)
I/flutter ( 6202): <asynchronous suspension>
I/flutter ( 6202): #2      AddressSubscriptionWaiter.setupClientListener.<anonymous closure> (package:raven_back/waiters/address_subscription.dart:38:11)       
I/flutter ( 6202): <asynchronous suspension>
I/flutter ( 6202): ----------------------------------------------------
```
So. What to do? it seems we either need to deal with locking the subscription handler, or, index the entire list of subscriptions by client, if maybe the client connection has some kind of unique ID? That way we can purge it for the old client, while at the same time adding stuff for the new client under a different heading...

**Comment by lastmeta** [comment]
by the way I haven't noticed this issue cause problems on the front end, and I don't think it would, but we need to solve it anyway. If it errors like this, it simply doesn't purge all the old subscriptions, which is not a major problem.

**Comment by lastmeta** [comment]
unawaiting the cancelation seemed to solve the issue
