### ISSUE TITLE
newline issue error

### ISSUE THREAD

**Issue by lastmeta** [moontreeapp/moontree#619]
### Describe The Bug

waiting for transactions to show up but I get an error about data from electrum

### To Reproduce

import all 3 wallets and wait for them to sync

### Expected Behavior

sync

### Log Output

```shell
I/flutter (18210): PINGING ELECTRUM SERVER
E/flutter (18210): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: FormatException: Unterminated string (at character 8192)
E/flutter (18210): ...00000003576a91477079d4860e4cb2b1f8e1a4c48cc9563b72f952788acc01972766e740c57
E/flutter (18210):                                                                               ^
E/flutter (18210):
E/flutter (18210): #0      _ChunkedJsonParser.fail package:raven_electrum/client/json_newline_transformer.dart:1460
E/flutter (18210): #1      _ChunkedJsonParser.close package:raven_electrum/client/json_newline_transformer.dart:599
E/flutter (18210): #2      _JsonStringDecoderSink.close package:raven_electrum/client/json_newline_transformer.dart:1563
E/flutter (18210): #3      _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:81:18)
E/flutter (18210): #4      _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
E/flutter (18210): #5      _rootRun (dart:async/zone.dart:1418:47)
E/flutter (18210): #6      _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (18210): #7      _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter (18210): #8      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)
E/flutter (18210): #9      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:7)
E/flutter (18210): #10     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
E/flutter (18210): #11     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
E/flutter (18210): #12     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
E/flutter (18210): #13     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
E/flutter (18210): #14     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:305:20)
E/flutter (18210): #15     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:81:18)
E/flutter (18210): #16     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
E/flutter (18210): #17     _rootRun (dart:async/zone.dart:1418:47)
E/flutter (18210): #18     _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (18210): #19     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter (18210): #20     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)
E/flutter (18210): #21     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:7)
E/flutter (18210): #22     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
E/flutter (18210): #23     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:782:19)
E/flutter (18210): #24     _StreamController._closeUnchecked (dart:async/stream_controller.dart:637:7)
E/flutter (18210): #25     _StreamController.close (dart:async/stream_controller.dart:630:5)
E/flutter (18210): #26     _Socket._onError (dart:io-patch/socket_patch.dart:2338:19)
E/flutter (18210): #27     _rootRunBinary (dart:async/zone.dart:1450:47)
E/flutter (18210): #28     _CustomZone.runBinary (dart:async/zone.dart:1342:19)
E/flutter (18210): #29     _CustomZone.runBinaryGuarded (dart:async/zone.dart:1252:7)
E/flutter (18210): #30     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:360:15)
E/flutter (18210): #31     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:375:9)
E/flutter (18210): #32     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:280:7)
E/flutter (18210): #33     _SyncStreamControllerDispatch._sendError (dart:async/stream_controller.dart:778:19)
E/flutter (18210): #34     _StreamController._addError (dart:async/stream_controller.dart:656:7)
E/flutter (18210): #35     _StreamController.addError (dart:async/stream_controller.dart:610:5)
E/flutter (18210): #36     _RawSecureSocket._reportError (dart:io/secure_socket.dart:771:19)
E/flutter (18210): #37     _rootRunBinary (dart:async/zone.dart:1450:47)
E/flutter (18210): #38     _CustomZone.runBinary (dart:async/zone.dart:1342:19)
E/flutter (18210): #39     _CustomZone.runBinaryGuarded (dart:async/zone.dart:1252:7)
E/flutter (18210): #40     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:360:15)
E/flutter (18210): #41     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:378:7)
E/flutter (18210): #42     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:280:7)
E/flutter (18210): #43     _SyncStreamControllerDispatch._sendError (dart:async/stream_controller.dart:778:19)
E/flutter (18210): #44     _StreamController._addError (dart:async/stream_controller.dart:656:7)
E/flutter (18210): #45     _StreamController.addError (dart:async/stream_controller.dart:610:5)
E/flutter (18210): #46     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1852:23)
E/flutter (18210): #47     _rootRunBinary (dart:async/zone.dart:1458:13)
E/flutter (18210): #48     _CustomZone.runBinary (dart:async/zone.dart:1342:19)
E/flutter (18210): #49     _CustomZone.runBinaryGuarded (dart:async/zone.dart:1252:7)
E/flutter (18210): #50     _CustomZone.bindBinaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1287:33)
E/flutter (18210): #51     _NativeSocket.reportError (dart:io-patch/socket_patch.dart:1562:32)
E/flutter (18210): #52     _NativeSocket.multiplex (dart:io-patch/socket_patch.dart:1408:13)
E/flutter (18210): #53     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
E/flutter (18210):
```
```


### Additional Context

happens on a regular startup

### Screenshots

_No response_

### Tasks For This Bug

 - [ ] #

**Comment by lastmeta** [comment]
this seems to have happened because of a breakpoint I set during startup
